### ISSUE TITLE
Don't require `--with-4ti2` if 4ti2 is installed globally

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/4ti2gap#4]
It would be nice if `--with-4ti2` was not required; instead, if not given, I'd suggest to search for 4ti2 headers and library "in the usual places" -- in other words, just leave `FTIT_CPPFLAGS` and `FTIT_LDFLAGS` empty (actually, rename `FTIT_LDFLAGS` to `FTIT_LDADD`, then replace `FTIT_LDPATH` by a new `FTIT_LDFLAGS` which you leave empty if `--with-4ti2`  is not given, and set to `-R$FTIT/lib` otherwise.

This way, it becomes much easier for us (= GAP core team) to run CI tests that include 4ti2gap -- which we do for all distributed packages, to make sure we notice if changes we make break any packages. Right now this is broken for 4ti2gap, as it always fails for us.

**Comment by alfsan** [comment]
It is done, please report any problem if you have the opportunity to test it, thank you

**Comment by fingolfin** [comment]
Unfortunately this still was broken. A fix is now in PR #7 (in one of the commits there)
